### ISSUE TITLE
Periodic counter issue

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/automated-walk-bike-counter#52]
When I try to run after #48, I get the following error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ian/anaconda3/envs/automated-walk-bike-counter/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/ian/anaconda3/envs/automated-walk-bike-counter/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/itacid457/repos/automated-walk-bike-counter/automated_walk_bike_counter/gui/controller/main_controller.py", line 71, in update_video_canvas
    tracker.trackObjects(config)
  File "/mnt/c/Users/itacid457/repos/automated-walk-bike-counter/automated_walk_bike_counter/core/tracking/object_tracker.py", line 394, in trackObjects
    if config.save_periodic_counter and self.input_camera_type == "file":
AttributeError: 'Namespace' object has no attribute 'save_periodic_counter'
```

Any idea how to fix @vahedi25411?

**Comment by ian-r-rose** [comment]
Looks like some changes from #47 didn't get copied over t o #48

**Comment by vahedi25411** [comment]
parser.add_argument(
    "--save_periodic_counter",
    type=lambda x: (str(x).lower() == "true"),
    default=True,
    help="Whether to save the periodic counter.(Save counter in 15 minutes)",
)

parser.add_argument(
    "--periodic_counter_time",
    type=int,
    default=15,
    help="Time frame to generate the periodic counter.(in minutes)",
)

These lines of code should be added to configuration.py .

**Comment by ian-r-rose** [comment]
This is now fixed
