### ISSUE TITLE
Possible to use yolov3-tiny?

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/automated-walk-bike-counter#64]
Related to #49 , since the other weights files seem to be missing, I took a crack at `yolov3-tiny`, but `convert_weights.py` failed with error: 

```python
Traceback (most recent call last):
  File "convert_weight.py", line 37, in <module>
    load_ops = load_weights(tf.global_variables(scope="yolov3"), weight_path)
  File "/home/ian/repos/automated-walk-bike-counter/automated_walk_bike_counter/utils/misc_utils.py", line 138, in load_weights
    (shape[3], shape[2], shape[0], shape[1])
ValueError: cannot reshape array of size 391699 into shape (512,256,3,3)
```

It looks like there are a fair number of hard-coded values in `automated-walk-bike-counter.core.model`. Might some of them need to be changed for this to work @vahedi25411?

**Comment by ian-r-rose** [comment]
@vahedi25411 Can you comment on whether this is worth it to set up?
